### ISSUE TITLE
Need input of dimension 4

### ISSUE THREAD

**Issue by fairuzsafwan** [Amir-Arsalan/Synthesize3DviaDepthOrSil#1]
I have my own trained models (AllVPNet and dropoutNet) trained from ShapeNet Core with my own 20 determined viewpoints with the default settings @epoch80 and batchsize of 4. Both networks are trained on depth maps.

However, I encountered the following error when I tried to output the results for "Random silhouettes/depth maps from user"

Error thrown:
Need input of dimension 4 and input.size[1] == 20 but got input to be of shape: [2 x 1 x 224 x 224]

The input of 20 depth maps are produced with the provided renderDepth program.
The error occurred when trying to use my trained models AllVPNet and also dropoutNet.

However, it worked when I used the originally provided pre-trained model "singleVPNet". 
The provided pre-trained model "AllVPNet" and "dropoutNet" also didn't worked.

or could it be that using my own depth maps in "userData" only works for singleVPNet?
If so, how could I get it work with AllVPNet and/or dropoutNet?

I would like to produce results from my own trained network AllVPNet and dropoutNet from an input of 20 depth maps but could not get it to work so far.

Any help is really much appreciated

Thanks in advance

**Comment by Amir-Arsalan** [comment]
@fairuzsafwan The problem is due to the nature of the "UserData" experiment. In this experiment, the assumption is to use a SingleVPNet and input a single-channel image and get a 3D reconstruction. Based on what you described, it seems that you are using a network whose input is a 20-channel signal/image but you are trying to input a single-channel image instead. AllVPNet and DropoutNet require their inputs to be 20-channel; that's why the SingleVPNet models work. Let me know if you need more clarity.

**Comment by fairuzsafwan** [comment]
Thank you very much for the response.

Is there any way to reconstruct a 3D model from my own depth map images of 20 using my trained AllVPNet and dropoutNet instead of only using singleVPNet?

**Comment by Amir-Arsalan** [comment]
Sorry I'm a little bit confused. If you are training the models with your own data, how come you are not able to reconstruct the 3D models of your own depth maps/silhouettes? Basically, as long as you have the 20 depth maps/silhouettes and have the corresponding camera angles that you used for rendering you must be able to produce the 3D shapes. Maybe you need to elaborate more on your question so that I can help you better.
